config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do ... end
  
  resources :cabinet do
	collection do
		get   'orders'
		get   'orders/:list_type', action: 'orders'
		get   'discounts'
		get   'cart', action: 'show', controller: 'carts'
		get   'e-commerce'
		
		if(defined?(MARKETPLACE_MODE_ONLINE_SHOP) && (MARKETPLACE_MODE_ONLINE_SHOP != true))
			get   'sellers'
		end
	end
  end

  resources :user, except: [:update, :edit] do
	collection do
		get   'profile'
		match 'profile_edit', via: [:get, :post]
		match 'profile_fill', via: [:get, :post]
		get   'wait_confirm'
		get   'payments/:list', action: 'payments'
		get   'payments', action: 'payments'
	end
  end
  
  resources :orders do
	collection do
		get   'begin', controller: 'carts', action: 'show', change_qnt: false
		get   'express', controller: 'carts', action: 'show', change_qnt: false
		
		get   'start', action: 'begin'
		post  'begin', action: 'begin'
		post  'express'
		match 'new', action: 'new', via: [:get, :post]
		match 'pay', action: 'pay', via: [:get, :post], controller: 'payments'
		get   'show/:order_uid', action: 'show', item_uid: nil
		post  'delete'
		match 'cancel', via: [:get, :post]
		post  'cancel.json', action: 'cancel'
		
		scope :change, :as => 'change' do
			post  'delivery_charges.json', action: 'change_delivery_charges'
			post  'agree.json', action: 'change_agree'
			post  'accept.json', action: 'change_accept'
			post  'delete_item.json', action: 'change_delete_item'
			get   'delete_item', action: 'change_delete_item'
		end
	end
  end
  
  resources :products do
	collection do
		get   'import'
		get   'import_groups', action: 'import', constraints: { format: 'html' }
		get   'import_products', action: 'import', constraints: { format: 'html' }
		get   'import_products_save', action: 'import', constraint: { format: 'html' }
		
		post  'import', action: 'import_price'
		post  'import_groups', action: 'import_price_groups_save'
		post  'import_products', action: 'import_price_products'
		post  'import_products_save', action: 'import_price_products_save'
		
		scope :update, :as => 'update' do
			get   'with_suppliers', action: 'update_with_suppliers'
			get   'with_suppliers_save', action: 'update_with_suppliers'
			post  'with_suppliers_save', action: 'update_with_suppliers_save'
		end
		
		post  'images_edit', action: 'images_edit'
		post  'images_add.json', action: 'images_add', constraints: { format: 'json' }
		post  'images_delete.json', action: 'images_delete', constraints: { format: 'json' }
	end
  end
  
  get   '/product/:pub_id', controller: 'products', action: 'show'
  get   '/product/archive/order/:order_safe_uid.:order_safe_uid_part/:pub_id', controller: 'products', action: 'show_archived'
  
  resources :payments do
	collection do
		match 'pay', action: 'pay', via: [:get, :post]
		
	end
  end
  
  resources :customers, except: [:destroy] do
	collection do
		match ':id/delete(.:format)', action: 'destroy', via: [:get, :post]
	end
  end
  
  resources :destinations, except: [:show, :destroy] do
	collection do
		match ':id/delete(.:format)', action: 'destroy', via: [:get, :post]
	end
  end
  
  get   '/payment/check_order/', controller: 'payments', action: 'check_order', production_mode: true
  post  '/payment/check_order/', controller: 'payments', action: 'check_order', production_mode: true
  post  '/payment/success/', controller: 'payments', action: 'success', production_mode: true
  get   '/payment/onsucceed/', controller: 'payments', action: 'onsucceed', production_mode: true
  get   '/payment/onfailure/', controller: 'payments', action: 'onfailure', production_mode: true
  get   '/payment/test/check_order/', controller: 'payments', action: 'check_order', production_mode: false
  post  '/payment/test/check_order/', controller: 'payments', action: 'check_order', production_mode: false
  post  '/payment/test/success/', controller: 'payments', action: 'success', production_mode: false
  get   '/payment/test/onsucceed/', controller: 'payments', action: 'onsucceed', production_mode: false
  get   '/payment/test/onfailure/', controller: 'payments', action: 'onfailure', production_mode: false
  
  get   '/catalog/:cat_group_id/f/:brand_name/:model_name/:model_year_num', controller: 'products', action: 'show_list'
  get   '/catalog/:cat_group_id/f/:brand_name/:model_name', controller: 'products', action: 'show_list'
  get   '/catalog/:cat_group_id/f/:brand_name', controller: 'products', action: 'show_list'
  get   '/catalog/:cat_group_id', controller: 'products', action: 'show_list'
  get   '/catalog/', controller: 'products', action: 'show_list'
  
  get   '/cart/show', controller: 'carts', action: 'show', change_qnt: false
  post  '/cart/show', controller: 'carts', action: 'show', change_qnt: true
  post  '/cart/change_item.json', controller: 'carts', action: 'change_item'
  post  '/cart/delete_item.json', controller: 'carts', action: 'delete_item'
  post  '/cart/is_in_cart.json', controller: 'carts', action: 'is_in_cart'
  
  resources :pay_invoices do
	collection do
		get  'show', action: 'show', print_ver: false
		get  'print', action: 'show', print_ver: true
		get  'print.pdf', action: 'show', print_ver: true, constraints: { format: 'pdf' }
	end
  end
  
  resources :search, only: [:index] do
	collection do
		post '', action: 'index'
	end
  end
  
  post  '/auto/:brand_name.json', controller: 'gen_brands', action: 'get_submodels'
  post  '/auto/:brand_name/:model_name.json', controller: 'gen_brands', action: 'get_submodel_years'
  get   '/auto/:brand_name', controller: 'products', action: 'show_list'
  #get   '/auto/:brand_name/:model', controller: 'products', action: 'show_list', list_filter: :model
  
  get   '/faq/:text_id', controller: 'content_pages', action: 'show'
  get   '/contacts/', controller: 'content_pages', action: 'show', text_id: 'contacts'
  get   '/privacy/', controller: 'content_pages', action: 'show', text_id: 'privacy_policy'
  get   '/for-buyers/', controller: 'content_pages', action: 'show', text_id: 'terms_sale'

  ## USERS LOGON
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => { sessions: "user/sessions", passwords: "user/passwords", registrations: "user/registrations" } #, skip: [:registrations]#, :controllers => { omniauth_callbacks: 'omniauth_callbacks' } #, :controllers => { sessions: "users/track_sessions" }
  
  ## ERRORS
  get   'error/403' => 'welcome#error_403'
  get   'error/404' => 'welcome#error_404'
  get   'error/denied', controller: 'welcome', action: 'error_access_denied'
  
  ## SPAM-VIRUS ROBOTS
  match 'admin' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'admin:smth' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'admin:smth/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'wp-login.php' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'webdav' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'myadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'MyAdmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'mysqladmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'mysql/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'websql/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'dbadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'db/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpmyadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpmyadmin:smth/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpMyAdmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpMyAdmin:smth/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'php-my-admin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'pma/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'scripts/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'bitrix/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'typo3/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'fck/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'xampp/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'muieblackcat' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'web/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'HNAP1' => 'welcome#error_RobotTryLogin', via: [:get, :post] # Routers Home Network Administration Protocol
  match 'modules/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'wp-content:smth' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'cgi-bin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'moadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'catalog/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'shop/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match '/CFIDE/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post] # ColdFusion

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do

app/models/cabinet.rb
class Cabinet < ActiveRecord::Base # Абстрактный класс, дабы работал Pundit.
	self.abstract_class = true
	
	
	
	### ======================================================================== PRIVATE ===============================================================================
	### ================================================================================================================================================================
	private
	
end

app/controllers/cabinet_controller.rb
class CabinetController < ApplicationController
	before_action :authenticate_and_authorize_user_action, :except => [:e_commerce]
	after_action  :verify_authorized, :except => [:e_commerce]
	
	before_action :prepare_inside_cabinet, :except => [:e_commerce]
	
	def index
		@is_allowed_to_ecommerce = current_user.is_allowed_to_ecommerce?
	end
	
	
	def e_commerce
		if(!user_signed_in?)
			render 'welcome/ad_ecommerce'
			return
		end
		
		authenticate_and_authorize_user_action
		verify_authorized
		set_cabinet_breadcrumbs({:name => I18n.t(:commerce, scope: [:dt_ishop, :cabinet, :menu_crumb]), :active => true}, true)
		
		@is_allowed_to_ecommerce = current_user.is_allowed_to_ecommerce?
	end
	
	
	def orders
		pparams = params.permit(:list_type, :page)
		set_cabinet_breadcrumbs({:name => I18n.t(:orders, scope: [:dt_ishop, :cabinet, :menu_crumb]), :active => true}, true)
		
		page = ((pparams[:page].present? && pparams[:page].numeric?) ? pparams[:page].to_i : 1)
		per_page = 20
		
		@is_admin = current_user.is_admin?
		@is_moderator = (@is_admin or current_user.is?(:moderator_orders))
		
		ret = Order.list_orders(((pparams[:list_type].present?) ? pparams[:list_type] : nil), page, per_page, current_user, nil)
		
		@orders = ret[:orders]
		@title = ret[:title]
		@list_type = ret[:type]
		
		if(@orders.present? && (@orders.first.present?))
			@orders_ids = @orders.collect {|order| order[:id]}
			@prods_assemblies = OrdersProductsAssembly.where(order_id: @orders_ids).find_all
			@prods_assemblies = nil if(@prods_assemblies.first.blank?)
		end
		
		@order_safeid_params = Order.prepare_make_safe_id
		@prod_code_form = 0 # 0=Brand & ProdCode, 1=Artikul
	end

	
	def discounts
		set_cabinet_breadcrumbs({:name => I18n.t(:discounts, scope: [:dt_ishop, :cabinet, :menu_main]), :active => true}, true)
		render 'welcome/not_yet_available'
	end
	
	
	### =========== [ FULL MARKETPLACE ONLY ] ===========
	### =================================================
	if(MARKETPLACE_MODE_ONLINE_SHOP != true)
	
	
	end
	
	
	### ======================================================================== PRIVATE ===============================================================================
	### ================================================================================================================================================================
	private
	
	def authenticate_and_authorize_user_action
		authenticate_user! # Devise authentication. It must be called after protect_from_forgery to CSRF-token work properly.
		authorize Cabinet # Pundit authorization.
	end
	
	
	def prepare_inside_cabinet
		@inside_cabinet = true
		set_cabinet_breadcrumbs(nil, false)
	end
end

app/helpers/cabinet_helper.rb
module CabinetHelper
end

app/views/cabinet/_menu_block_ecommerce.html.slim
# encoding: UTF-8

- ts_icab_ms = [:dt_ishop, :cabinet, :menu_main_seller]

div[class="menu-block block-col block-wd-half menu-sellers"]
  div[class="menu-item"]
    div[class="item-title"]= link_to I18n.t(:import_price, scope: ts_icab_ms), import_products_path
    div[class="item-desc"]#{I18n.t(:import_price_desc, scope: ts_icab_ms)}
  div[class="menu-item"]            
    div[class="item-title"]= link_to I18n.t(:prod_update_from_suppliers, scope: ts_icab_ms), with_suppliers_update_products_path
    div[class="item-desc"]#{I18n.t(:prod_update_from_suppliers_desc, scope: ts_icab_ms)}

div[class="menu-block block-col block-wd-half menu-sellers"]
  div[class="menu-item disabled"]
    div[class="item-title"]= link_to I18n.t(:import_own_wrh, scope: ts_icab_ms), '#'
    div[class="item-desc"]#{I18n.t(:import_own_wrh_desc, scope: ts_icab_ms)}
  div[class="menu-item disabled"]            
    div[class="item-title"]= link_to I18n.t(:prod_update_from_own_wrh, scope: ts_icab_ms), '#'
    div[class="item-desc"]#{I18n.t(:prod_update_from_own_wrh_desc, scope: ts_icab_ms)}

app/views/cabinet/_menu_cabinet.html.slim
# encoding: UTF-8

ol[class="breadcrumb cabinet-breadcrumb"]
  = render_breadcrumbs :tag => :li, :separator => "", :html => {:class => "breadcrumb-item"}

app/views/cabinet/e_commerce.html.slim
# encoding: UTF-8

div[class="cabinet-mainpage"]
  div[class="page-block padding-more menu-block"]
    div[class="row"]
      - if(@is_allowed_to_ecommerce)
        div[class="col-md-9"]
          div[class="row"]
            = render 'menu_block_ecommerce'

        //div[class="col-md-3 block-border-left"]
          div[class="menu-block"]
            div[class="menu-item"]
              div[class="item-title"]= link_to "Выход", destroy_user_session_path, :method => :delete
      
      - else
        div[class="col-md-12"]
          = render file: 'welcome/error_access_denied'
          // p Если Вы попали сюда случайно, возможно, Вас интересует кто создал данный интернет-магазин ?

app/views/cabinet/index.html.slim
# encoding: UTF-8

- content_for :html_title do
  | #{@txt_cabinet_html_title}

div[class="cabinet-mainpage"]
  div[class="page-block padding-more menu-block"]
    div[class="row"]
      div[class="col-md-9"]
        div[class="row"]
          div[class="menu-block block-col block-wd-half"]
            div[class="menu-item"]
              div[class="item-title"]= link_to I18n.t(:profile, scope: [:dt_ishop, :cabinet, :menu_main]), user_index_path
              div[class="item-desc"]#{I18n.t(:profile_desc, scope: [:dt_ishop, :cabinet, :menu_main])}
            div[class="menu-item"]
              div[class="item-title"]= link_to I18n.t(:cart, scope: [:dt_ishop, :cabinet, :menu_main]), cart_cabinet_index_path
              div[class="item-desc"]#{I18n.t(:cart_desc, scope: [:dt_ishop, :cabinet, :menu_main])}
			// div[class="menu-item disabled"]
              div[class="item-title"]= link_to I18n.t(:discounts, scope: [:dt_ishop, :cabinet, :menu_main]), discounts_cabinet_index_path
              div[class="item-desc"]#{I18n.t(:discounts_desc, scope: [:dt_ishop, :cabinet, :menu_main])}
        
          div[class="menu-block block-col block-wd-half"]
            div[class="menu-item"]
              div[class="item-title"]= link_to I18n.t(:orders, scope: [:dt_ishop, :cabinet, :menu_main]), orders_cabinet_index_path
              div[class="item-desc"]#{I18n.t(:orders_desc, scope: [:dt_ishop, :cabinet, :menu_main])}
            div[class="menu-item"]
              div[class="item-title"]= link_to I18n.t(:payments, scope: [:dt_ishop, :cabinet, :menu_main]), payments_user_index_path
              div[class="item-desc"]#{I18n.t(:payments_desc, scope: [:dt_ishop, :cabinet, :menu_main])}
            div[class="menu-item"]
        
        - if(@is_allowed_to_ecommerce)
          div[class="row"]
            div[class="col"]
              h5 #{I18n.t(:commerce, scope: [:dt_ishop, :cabinet, :menu_main])}
              hr
          div[class="row"]
            = render 'menu_block_ecommerce'
        
      div[class="col-md-3 block-border-left"]
        div[class="menu-block"]
          div[class="menu-item"]
            div[class="item-title"]= link_to I18n.t(:logout1, scope: [:dt_breeze, :cabinet]), destroy_user_session_path, :method => :delete

app/views/cabinet/orders.html.slim
# encoding: UTF-8

- ts_ord = [:dt_ishop, :orders]

div[class="cabinet-mainpage"]
  div[class="page-block padding-more"]
    div[class="dyna-frame" id="dynaframe_orders_list" data-url="#{request.original_fullpath}"]
      div[id="dynaframe_orders_list_content" class="dyna-frame-content"]
        h1 #{(@title.present?) ? @title : t(:orders, scope: ts_ord)}
        div[class="page-menu"]
          - path = orders_cabinet_index_path
          <a href="#{path}/new" #{(@list_type != 'new') ? '' : 'class=active'}>#{t(:orders_new, scope: ts_ord)}</a>
          <a href="#{path}/wait_pay" #{(@list_type != 'wait_pay') ? '' : 'class=active'}>#{t(:orders_wait_pay, scope: ts_ord)}</a>
          <a href="#{path}/wait_delivery" #{(@list_type != 'wait_delivery') ? '' : 'class=active'}>#{t(:orders_wait_delivery, scope: ts_ord)}</a>
          <a href="#{path}/delivered" #{(@list_type != 'delivered') ? '' : 'class=active'}>#{t(:orders_delivered, scope: ts_ord)}</a>
          <a href="#{path}/cancelled" #{(@list_type != 'cancelled') ? '' : 'class=active'}>#{t(:orders_cancelled, scope: ts_ord)}</a>
          <a href="#{path}/archive" #{(@list_type != 'archive') ? '' : 'class=active'}>#{t(:orders_archive, scope: ts_ord)}</a>
          <a href="#{path}/all" #{(@list_type != 'all') ? '' : 'class=active'}>#{t(:orders_all, scope: ts_ord)}</a>
        
        - if(@orders.present? && (@orders.size > 0))
          div[class="orders-list-lite t-table t-collapse"]
            - @orders.each do |order|
              = render 'orders/table_order_info', order: order
            
            div[class="page_pagination"]
              = will_paginate @orders, :container => false
        - elsif(@list_type == 'new')
          p #{t(:new_orders_not_found, scope: ts_ord)}
        - else
          p #{t(:orders_not_found, scope: ts_ord)}


javascript:
  function orders_list_onclick(event){
    etarget = $(event.target);
    if(etarget.is(".order-items .product .btn-delete")){
      prod = etarget.parents(".product:first");
      oitem_id = prod.attr("data-product-uid");
      oid = prod.parents("div[data-order-id]:first").attr('data-order-id')
      panel = prod.parents(".order-items:first");
      sq_params = {'frame_id': null, 'wait_block': panel.attr("id"), 'handler_func': 'fn_wnd_need_orders_list_update', 'no_status_ok': true, 'd_order_uid': oid, 'd_item_uid': oitem_id};
      window['OnFlyEG_QueryUrl'](panel.attr("id"), '/orders/change/delete_item', 'post', 'json', null, sq_params);
      event.preventDefault();
    }
  }
  
  window['need_orders_list_update'] = function (ret,panel_id,form_id,b_delayed,query,ret_success,data,jqxhr){
    if(ret_success != null){
      sq_params = {'frame_id': "dynaframe_orders_list", 'wait_block': "dynaframe_orders_list", 'handler_func': window['on_orders_list_updated'], 'no_status_ok': true, 'd_order_uid': "#{@order_uid}"};
      window['OnFlyEG_QueryUrl']("cabinet_mainpage", null, 'get', 'html', null, sq_params);
    }
  }
  
  window["orders_list_onload"] = function (page_frame){
    $(document).on("click", orders_list_onclick);
  }
  
  window["orders_list_teardown"] = function (page_frame){
    $(document).off("click", orders_list_onclick);
  }
  
  $(document).on("ready turbolinks:load", window["orders_list_onload"]);
  $(document).on("turbolinks:before-cache", window["orders_list_teardown"]);