config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do ... end
  
  resources :cabinet do
	collection do
		get   'orders'
		get   'orders/:list_type', action: 'orders'
		get   'discounts'
		get   'cart', action: 'show', controller: 'carts'
		get   'e-commerce'
		
		if(defined?(MARKETPLACE_MODE_ONLINE_SHOP) && (MARKETPLACE_MODE_ONLINE_SHOP != true))
			get   'sellers'
		end
	end
  end

  resources :user, except: [:update, :edit] do
	collection do
		get   'profile'
		match 'profile_edit', via: [:get, :post]
		match 'profile_fill', via: [:get, :post]
		get   'wait_confirm'
		get   'payments/:list', action: 'payments'
		get   'payments', action: 'payments'
	end
  end
  
  resources :orders do
	collection do
		get   'begin', controller: 'carts', action: 'show', change_qnt: false
		get   'express', controller: 'carts', action: 'show', change_qnt: false
		
		get   'start', action: 'begin'
		post  'begin', action: 'begin'
		post  'express'
		match 'new', action: 'new', via: [:get, :post]
		match 'pay', action: 'pay', via: [:get, :post], controller: 'payments'
		get   'show/:order_uid', action: 'show', item_uid: nil
		post  'delete'
		match 'cancel', via: [:get, :post]
		post  'cancel.json', action: 'cancel'
		
		scope :change, :as => 'change' do
			post  'delivery_charges.json', action: 'change_delivery_charges'
			post  'agree.json', action: 'change_agree'
			post  'accept.json', action: 'change_accept'
			post  'delete_item.json', action: 'change_delete_item'
			get   'delete_item', action: 'change_delete_item'
		end
	end
  end
  
  resources :products do
	collection do
		get   'import'
		get   'import_groups', action: 'import', constraints: { format: 'html' }
		get   'import_products', action: 'import', constraints: { format: 'html' }
		get   'import_products_save', action: 'import', constraint: { format: 'html' }
		
		post  'import', action: 'import_price'
		post  'import_groups', action: 'import_price_groups_save'
		post  'import_products', action: 'import_price_products'
		post  'import_products_save', action: 'import_price_products_save'
		
		scope :update, :as => 'update' do
			get   'with_suppliers', action: 'update_with_suppliers'
			get   'with_suppliers_save', action: 'update_with_suppliers'
			post  'with_suppliers_save', action: 'update_with_suppliers_save'
		end
		
		post  'images_edit', action: 'images_edit'
		post  'images_add.json', action: 'images_add', constraints: { format: 'json' }
		post  'images_delete.json', action: 'images_delete', constraints: { format: 'json' }
	end
  end
  
  get   '/product/:pub_id', controller: 'products', action: 'show'
  get   '/product/archive/order/:order_safe_uid.:order_safe_uid_part/:pub_id', controller: 'products', action: 'show_archived'
  
  resources :payments do
	collection do
		match 'pay', action: 'pay', via: [:get, :post]
		
	end
  end
  
  resources :customers, except: [:destroy] do
	collection do
		match ':id/delete(.:format)', action: 'destroy', via: [:get, :post]
	end
  end
  
  resources :destinations, except: [:show, :destroy] do
	collection do
		match ':id/delete(.:format)', action: 'destroy', via: [:get, :post]
	end
  end
  
  get   '/payment/check_order/', controller: 'payments', action: 'check_order', production_mode: true
  post  '/payment/check_order/', controller: 'payments', action: 'check_order', production_mode: true
  post  '/payment/success/', controller: 'payments', action: 'success', production_mode: true
  get   '/payment/onsucceed/', controller: 'payments', action: 'onsucceed', production_mode: true
  get   '/payment/onfailure/', controller: 'payments', action: 'onfailure', production_mode: true
  get   '/payment/test/check_order/', controller: 'payments', action: 'check_order', production_mode: false
  post  '/payment/test/check_order/', controller: 'payments', action: 'check_order', production_mode: false
  post  '/payment/test/success/', controller: 'payments', action: 'success', production_mode: false
  get   '/payment/test/onsucceed/', controller: 'payments', action: 'onsucceed', production_mode: false
  get   '/payment/test/onfailure/', controller: 'payments', action: 'onfailure', production_mode: false
  
  get   '/catalog/:cat_group_id/f/:brand_name/:model_name/:model_year_num', controller: 'products', action: 'show_list'
  get   '/catalog/:cat_group_id/f/:brand_name/:model_name', controller: 'products', action: 'show_list'
  get   '/catalog/:cat_group_id/f/:brand_name', controller: 'products', action: 'show_list'
  get   '/catalog/:cat_group_id', controller: 'products', action: 'show_list'
  get   '/catalog/', controller: 'products', action: 'show_list'
  
  get   '/cart/show', controller: 'carts', action: 'show', change_qnt: false
  post  '/cart/show', controller: 'carts', action: 'show', change_qnt: true
  post  '/cart/change_item.json', controller: 'carts', action: 'change_item'
  post  '/cart/delete_item.json', controller: 'carts', action: 'delete_item'
  post  '/cart/is_in_cart.json', controller: 'carts', action: 'is_in_cart'
  
  resources :pay_invoices do
	collection do
		get  'show', action: 'show', print_ver: false
		get  'print', action: 'show', print_ver: true
		get  'print.pdf', action: 'show', print_ver: true, constraints: { format: 'pdf' }
	end
  end
  
  resources :search, only: [:index] do
	collection do
		post '', action: 'index'
	end
  end
  
  post  '/auto/:brand_name.json', controller: 'gen_brands', action: 'get_submodels'
  post  '/auto/:brand_name/:model_name.json', controller: 'gen_brands', action: 'get_submodel_years'
  get   '/auto/:brand_name', controller: 'products', action: 'show_list'
  #get   '/auto/:brand_name/:model', controller: 'products', action: 'show_list', list_filter: :model
  
  get   '/faq/:text_id', controller: 'content_pages', action: 'show'
  get   '/contacts/', controller: 'content_pages', action: 'show', text_id: 'contacts'
  get   '/privacy/', controller: 'content_pages', action: 'show', text_id: 'privacy_policy'
  get   '/for-buyers/', controller: 'content_pages', action: 'show', text_id: 'terms_sale'

  ## USERS LOGON
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => { sessions: "user/sessions", passwords: "user/passwords", registrations: "user/registrations" } #, skip: [:registrations]#, :controllers => { omniauth_callbacks: 'omniauth_callbacks' } #, :controllers => { sessions: "users/track_sessions" }
  
  ## ERRORS
  get   'error/403' => 'welcome#error_403'
  get   'error/404' => 'welcome#error_404'
  get   'error/denied', controller: 'welcome', action: 'error_access_denied'
  
  ## SPAM-VIRUS ROBOTS
  match 'admin' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'admin:smth' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'admin:smth/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'wp-login.php' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'webdav' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'myadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'MyAdmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'mysqladmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'mysql/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'websql/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'dbadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'db/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpmyadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpmyadmin:smth/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpMyAdmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'phpMyAdmin:smth/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'php-my-admin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'pma/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'scripts/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'bitrix/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'typo3/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'fck/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'xampp/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'muieblackcat' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'web/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'HNAP1' => 'welcome#error_RobotTryLogin', via: [:get, :post] # Routers Home Network Administration Protocol
  match 'modules/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'wp-content:smth' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'cgi-bin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'moadmin/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'catalog/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match 'shop/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post]
  match '/CFIDE/*other' => 'welcome#error_RobotTryLogin', via: [:get, :post] # ColdFusion

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do

app/models/customer.rb
class Customer < AccessListModel
	has_one    :balance, :foreign_key => :id, :primary_key => :balance_id
	
	scope :order_by_usage, -> {order('use_count DESC, created_at DESC')}
	
	
	@@shstr_norm  = [...]
	@@shstr_shuff = [...]
	
	@partner = nil
	
	
	def self.compare_with_info (customer_id, hinfo)

		return true
	end
	
	
	def fill_info (hinfo)
		
	end
	
	
	def pub_name
		if(self.customer_type == CUSTOMER_TYPE_LEGAL)
			
		else
			
		end
		
	end
	
	
	def self.sorted_customers_list (user_id, customers_ids, current_customer_id)
		if(user_id.nil?)
			user_customers = Customer.where(id: customers_ids, is_deleted: false).order_by_usage.find_all
		else
			user_customers = Customer.where(id: customers_ids, user_id: user_id, is_deleted: false).order_by_usage.find_all
		end
		
		if(user_customers.present? && user_customers.first.present?)

		
		end
		return nil
	end
	
	
	def self.validate_required_params_before_create (pparams, emails_to_scram = nil)
		
		
		return {'status' => 'error', 'status_text' => err_json_text, 'bad_fields' => err_bad_fields, 'bad_reasons' => err_bad_fields_why }
	end
	
	
	# ENCODED PAY-SERVICE ID WITH CRC HASH
	def static_pub_safe_uid (safeid_params = nil, uri_encode = false)
		
	end
	
	
	def self.prepare_make_safe_id
		
	end
	
	
	def self.pub_safe_uid(safeid_params, pid, gen_params_if_nil = false, uri_encode = false)
		
	end
	
	
	def self.from_safe_uid (pub_safe_id)
		
	end
	
	
	def self.contacts_mails_list (object)
		contacts_list = {}
		customer_contacts = object.customer_contacts
		if(customer_contacts.present?)
			skip = 0
			for i in 1..3
				
				
				break if(skip >= 2)
			end
		end
		return contacts_list
	end
	
	
	# кто подписан на уведомления о покупках
	def users_list_subscribed_to_purchase
		return {self.user_id => nil, 'customer' => Customer.contacts_mails_list(self)}
	end
	
	
	# кто подписан на уведомления об изменении информации о покупателе
	def users_list_subscribed_to_changes
		return {self.user_id => nil, 'customer' => Customer.contacts_mails_list(self)}
	end
	
	
	# кто может подтвердить разрешение на изменение информации о покупателе
	def users_list_can_confirm_changes
		return {self.user_id => nil, 'customer' => Customer.contacts_mails_list(self)}
	end
	
	
	
	## ======================================== ##
	##     ACL - Access List Rights Model       ##
	## ======================================== ##
	
	RIGHTS = {
		# Права покупателя:
		
	}
	
	def rights_list
		RIGHTS
	end
	
	#Verify the access after Main Rights verification
	def object_has_access? (rights, pAccessList = @rAcl)
		ret_access = pAccessList.user_is?([:admin, :super_admin, :moderator_users])
		if(!ret_access)
			ret_access = pAccessList.is_any_right?([:owner])
			
			if(!ret_access && self.user_id.present? && (self.user_id != 0))
				
			end
			
			if(!ret_access && self.partner_id.present? && (self.partner_id != 0))
				@partner = Partner.where(id: self.partner_id).first if(@partner.nil?)
				if(@partner.present?)
					
					
				end
			end
		end
		return ret_access
	end
	
	
	### =================================== PROTECTED ==========================================
	### ========================================================================================
	protected
	
	
	### ==================================== PRIVATE ===========================================
	### ========================================================================================
	private
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer_info.html.slim
# encoding: UTF-8

- if(!defined?(allow_legal_info))
  - allow_legal_info = @allow_legal_info

- if(!defined?(allow_contacts))
  - allow_contacts = @allow_contacts

- if(!defined?(customer))
  - customer = @customer

- if(!defined?(scram_emails) or scram_emails.nil? or (scram_emails.is_a?(Array) && scram_emails.blank?))
  - scram_emails = true

- if(!defined?(as_profile_widgets))
  - as_profile_widgets = false

- if(allow_legal_info or allow_contacts)
  div[class="customer-details"]
    div[class="customer-type"]
      - txt = nil
      - orgtype = 0
      - if(customer[:customer_type] == CUSTOMER_TYPE_FIZ_LICO)
        - txt = ORGANIZATION_TYPES[ORGANIZATION_TYPE_FIZ_LICO][:full]
      - elsif(customer[:customer_legal_info].present?)
        - if(customer[:customer_legal_info]['orgtype'].present?)
          - orgtype = customer[:customer_legal_info]['orgtype'].to_i
          - if(ORGANIZATION_TYPES.has_key?(orgtype))
            - txt = ORGANIZATION_TYPES[orgtype][:full]
      
      - if(txt.nil?)
        - txt = 'Юридическое лицо'
      
      - if(!as_profile_widgets)
        span[class="info-title"]Тип покупателя:&nbsp;
      span[class="info-text"]#{txt}

    - if(customer[:customer_type] == CUSTOMER_TYPE_LEGAL)
      - if(allow_legal_info)
        - legal_info = customer[:customer_legal_info]
        - if(legal_info.present?)
          span[class="info-title cm-type"]#{(orgtype == ORGANIZATION_TYPE_IND_PREDP) ? 'ИП' : 'Наименование'}:&nbsp;
          span[class="info-text cm-name"]#{legal_info['name']}
          br
          span[class="info-title"]ОГРН:&nbsp;
          span[class="info-text"]#{legal_info['ogrn']}
          br
          span[class="info-title"]ИНН:&nbsp;
          span[class="info-text"]#{legal_info['inn']}
          - if(legal_info['kpp'].present?)
            |&nbsp;&nbsp;
            span[class="info-title"]КПП:&nbsp;
            span[class="info-text"]#{legal_info['kpp']}
          br
          - show_addr = (allow_contacts or (orgtype != ORGANIZATION_TYPE_IND_PREDP))
          span[class="info-title"]#{as_profile_widgets ? 'Юр. адрес ' : 'Юридический адрес'}:&nbsp;
          span[class="info-text"]#{show_addr ? legal_info['addr_ur'] : '***'}
          br
          - if(legal_info['addr_post'].present?)
            span[class="info-title"]Почтовый адрес:&nbsp;
            span[class="info-text"]#{show_addr ? legal_info['addr_post'] : '***'}
            br
          - if(orgtype != ORGANIZATION_TYPE_IND_PREDP)
            span[class="info-title"]Руководитель:&nbsp;
            span[class="info-text"]#{legal_info['dir_post']} #{legal_info['dir_name']}
            br
      - else
        div[class="status_block warn_info visible"]У вас нет доступа к информации о покупателе.
      
      br
      p: b Контактная информация:
    
    - if(allow_contacts)
      - if(customer[:customer_contacts].present?)
        - cont1_name  = customer[:customer_contacts]['name1']
        - cont1_email = customer[:customer_contacts]['email1']
        - cont1_phone = customer[:customer_contacts]['phone1']
        - cont2_name  = customer[:customer_contacts]['name2']
        - cont2_email = customer[:customer_contacts]['email2']
        - cont2_phone = customer[:customer_contacts]['phone2']
        
        - if(cont1_name.present? or cont1_email.present? or cont1_phone.present?)
          - if(cont1_name.blank?)
            - cont1_name = 'не указано'
          <p><span class="info-title">Имя:</span> <span class="info-text text-bold">#{cont1_name}</span><br>
          - if(cont1_email.present?)
            - email = ((scram_emails.is_a?(TrueClass) or (scram_emails.is_a?(Array) && scram_emails.include?(cont1_email))) ? User.email_hide_symbols(cont1_email) : cont1_email)
            |<span class="info-title">E-mail:</span> <span class="info-text text-bold">#{email}</span><br>
          - if(cont1_phone.present?)
            |<span class="info-title">Тел:</span><span class="info-text text-bold">#{cont1_phone}</span>
          </p>
          
        - if(cont2_name.present? or cont2_email.present? or cont2_phone.present?)
          - if(cont2_name.blank?)
            - cont2_name = 'не указано'
          <p><span class="info-title">Имя: <span class="info-text text-bold">#{cont2_name}</span><br>
          - if(cont2_email.present?)
            - email = ((scram_emails.is_a?(TrueClass) or (scram_emails.is_a?(Array) && scram_emails.include?(cont2_email))) ? User.email_hide_symbols(cont2_email) : cont2_email)
            |<span class="info-title">E-mail:</span> <span class="info-text text-bold">#{email}</span><br>
          - if(cont2_phone.present?)
            |<span class="info-title">Тел:</span><span class="info-text text-bold">#{cont2_phone}</span>
          </p>
    - else
      div[class="status_block warn_info visible"]У вас нет доступа к контактам покупателя.

- else
  div[class="status_block warn_info visible"]У вас нет доступа к информации о покупателе и его контактах.

app/views/customers/_list.html.slim
# encoding: UTF-8

- if(!defined?(customers))
  - customers = @customers

- if(!defined?(scram_emails))
  - scram_emails = nil

- if(!defined?(as_links))
  - as_links = true
  
div[class="customers list-flex align-items-start"]
  - customers.each do |customer|
    - customer_uid = customer.static_pub_safe_uid(@customer_safeid_params)
    - is_active_class = (@cur_customer_id.nil? or (@cur_customer_id != customer.id)) ? nil : 'active'
    
    - if(as_links)
      <a href="#{customer_path(id: customer_uid.gsub('.', '%2E'))}" class="customer list-item #{is_active_class}" title="#{is_active_class.nil? ? nil : 'Используется по-умолчанию'}">
    - else
      <span class="customer list-item #{is_active_class}" data-item-uid="#{customer_uid}">
    
    = render 'customers/customer_info', allow_legal_info: true, allow_contacts: true, scram_emails: scram_emails, customer: customer, as_profile_widgets: @as_profile_widgets
    
    - if(as_links)
      </a>
    - else
      </span>

app/views/customers/_list_select_box.html.slim
# encoding: UTF-8

- if(!defined?(customers))
  - customers = @customers

- if(customers.present?)  
  - safeid_params = Customer.prepare_make_safe_id
  
  select[class="custom-select" name="customer_select" required]
    - customers.each do |customer|
      - name = customer.pub_name
      - org_type = nil
      
      - if(customer[:customer_type] == CUSTOMER_TYPE_FIZ_LICO)
        - org_type = ORGANIZATION_TYPE_FIZ_LICO
      - elsif(customer[:customer_legal_info].present?)
        - if(customer[:customer_legal_info]['orgtype'].present?)
          - orgtype = customer[:customer_legal_info]['orgtype'].to_i
      
      - if(!org_type.nil?)
        - name = Document.name_and_type_lite(200, false, name, org_type)
      <option value="#{Customer.pub_safe_uid(safeid_params, customer.id, true)}" #{(@selected_customer_id == customer.id) ? 'selected' : ''}>#{name}</option>

app/views/customers/destroy.html.slim
# encoding: UTF-8

- ts_tcp = [:dt_ishop,  :cabinet, :profile]
- ts_msg = [:dt_breeze, :messages]

// Page Title
- page_header = t(:header_delete_customer, scope: ts_tcp)

- content_for :html_title do
  |#{page_header} - #{t(:html_title_short_part, scope: [:dt_breeze])}

div[class="cabinet-mainpage" id="cabinet_mainpage"]
  div[class="page-block padding-more"]
    h1 #{page_header}
    
    - if(@json_answer['status'] == 'ok')
      div[class="status_block success visible"]#{t(:msg_customer_deleted, ttext: @customer_name, scope: ts_tcp)}
    - else
      div[class="status_block error visible"]#{t(:Error, scope: ts_msg)}: #{(@json_answer['status_text'].present?) ? @json_answer['status_text'] : t(:error_unknown, scope: ts_msg)}

app/views/customers/edit.html.slim
# encoding: UTF-8

- ts_tcp = [:dt_ishop,  :cabinet, :profile]

// Page Title
- page_header = t(:header_customer_edit, scope: ts_tcp) 

- content_for :html_title do
  |#{page_header} - #{t(:html_title_short_part, scope: [:dt_breeze])}

div[class="cabinet-mainpage" id="cabinet_mainpage"]
  div[class="page-block padding-more"]
    h1 #{page_header}
    = render 'edit_fields', formobj: @customer

app/views/customers/new.html.slim
# encoding: UTF-8

// Page Title
- page_header = t(:header_new_customer, scope: [:dt_ishop, :cabinet, :profile]) 

- content_for :html_title do
  |#{page_header} - #{t(:html_title_short_part, scope: [:dt_breeze])}

div[class="cabinet-mainpage" id="cabinet_mainpage"]
  div[class="page-block padding-more"]
    h1 #{page_header}
    = render 'edit_fields'

app/views/customers/show.html.slim
# encoding: UTF-8

- ts_bcp = [:dt_breeze, :cabinet, :profile]
- ts_tcp = [:dt_ishop,  :cabinet, :profile]
- ts_msg = [:dt_breeze, :messages]
- ts_btn = [:dt_breeze, :buttons]

// Page Title
- page_header = t(:header_customer, scope: ts_tcp)

- content_for :html_title do
  |#{page_header} - #{t(:html_title_short_part, scope: [:dt_breeze])}

- customer_uid = Customer.pub_safe_uid(nil,@customer.id.to_i,true,true)

div[class="cabinet-mainpage" id="cabinet_mainpage"]
  div[class="page-block padding-more"]
    h1 #{page_header}
    <!--googleoff: all-->
    <!--noindex-->
    div[class="customer-full"]
      - @as_profile_widgets = true
      = render 'customer_info', allow_legal_info: @allow_legal_info, allow_contacts: @allow_contacts, customer: @customer, scram_emails: ((@user.nil?) ? true : [@user.email, @user.unconfirmed_email])
    a[href="#{edit_customer_path(id: customer_uid)}" class="button btn btn-border-4 btn-thin btn-margin-w"] #{t(:edit, scope: ts_btn)}
    a[href="#{'/customers/' + URI.encode(customer_uid) + '/delete'}" class="button btn btn-border-6 btn-thin btn-margin-w" data-with-ajax="get/json"] #{t(:delete, scope: ts_btn)}
    // = link_to t(:delete, scope: ts_btn), customer_path(id: customer_uid), :class => "button btn btn-border-6 btn-thin btn-margin-w", "data-with-ajax" => "get/json"
    
    p &nbsp;
    hr
    h2.blu #{t(:header_destinations, scope: ts_tcp)}
    - if(@destinations.nil?)
      a[href="#{new_destination_path(customer_uid: customer_uid)}" class="button btn clr4 btn-thin"] #{t(:add_delivery_loc, scope: [:dt_ishop, :buttons])}
    - else
      = render 'destinations/list', destinations: @destinations, link_to: 'edit', customer_uid: customer_uid
      a[href="#{new_destination_path(customer_uid: customer_uid)}" class="button btn btn-border-4 btn-thin"] #{t(:add_delivery_loc, scope: [:dt_ishop, :buttons])}
    
    
    <!--/noindex-->
    <!--googleon: all-->